name: Build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            runtime: linux-x64
            name: linux
          - os: windows-latest
            runtime: win-x64
            name: windows
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Build extension
      run: dotnet publish -c Release -r ${{ matrix.runtime }} --self-contained true -p:NativeLib=Shared -p:EnableCompressionInSingleFile=false
      working-directory: ./src
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tmp-${{ matrix.name }}
        path: src/GMInk/bin/Release/net*/${{ matrix.runtime }}/publish/
  
  package:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Linux artifacts
      uses: actions/download-artifact@v4
      with:
        name: tmp-linux
        path: src/output/
        
    - name: Download Windows artifacts
      uses: actions/download-artifact@v4
      with:
        name: tmp-windows
        path: src/output/
        
    - name: Upload combined artifacts
      uses: actions/upload-artifact@v4
      with:
        name: GMInk
        path: src/output/

