name: Build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            runtime: linux-x64
            name: linux
          - os: windows-latest
            runtime: win-x64
            name: windows
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.6'
        
    - name: Build extension
      run: dotnet publish -c Release -r ${{ matrix.runtime }} --self-contained
      working-directory: ./src

    - name: Prepare artifacts
      run: |
        mkdir artifacts
        cp src/GMInk/bin/Release/net*/${{ matrix.runtime }}/publish/* artifacts/
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tmp-${{ matrix.name }}
        path: artifacts/
  
  package:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Linux artifacts
      uses: actions/download-artifact@v4
      with:
        name: tmp-linux
        path: linux
        
    - name: Download Windows artifacts
      uses: actions/download-artifact@v4
      with:
        name: tmp-windows
        path: windows
    
    - name: Prepare artifacts
      run: |
        mkdir artifacts
        mv linux/* artifacts/
        mv windows/* artifacts/
        mv src/gm-files/* artifacts/
        
    - name: Upload combined artifacts
      uses: actions/upload-artifact@v4
      with:
        name: GMInk
        path: artifacts/

